In [52]:
%pip install geopandas

Requirement already satisfied: geopandas in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.0)
Requirement already satisfied: numpy>=2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from geopandas) (2.5.3)
Requirement already satisfied: packaging in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from geopandas) (26.3)
Requirement already satisfied: pandas>=2.2.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from geopandas) (3.0.6)
Requirement already satisfied: pyogrio>=0.8 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from geopandas) (0.13.0)
Requirement already satisfied: pyproj>=3.7.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from geopandas) (3.8.0)
Requirement already satisfied: shapely>=2.1.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=2.2.0->geopandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=2.2.0->geopandas) (2026.5)
Requirement already satisfied: certifi in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pyogrio>=0.8->geopandas) (2026.7.22)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->geopandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [53]:
import geopandas as gpd

In [54]:
gpd.__version__

'1.2.0'

In [57]:
import geopandas as gpd
from shapely.geometry import Point

data = {
    "City": ["Cape Town", "Johannesburg"],
    "Latitude": [-33.9249, -26.2041],
    "Longitude": [18.4241, 28.0473]
}

geometry = [
    Point(18.4241, -33.9249),
    Point(28.0473, -26.2041)
]

gdf = gpd.GeoDataFrame(data, geometry=geometry, crs="EPSG:4326")

gdf

           City  Latitude  Longitude                  geometry
0     Cape Town  -33.9249    18.4241  POINT (18.4241 -33.9249)
1  Johannesburg  -26.2041    28.0473  POINT (28.0473 -26.2041)

In [58]:
gdf[gdf["City"] == "Cape Town"]

        City  Latitude  Longitude                  geometry
0  Cape Town  -33.9249    18.4241  POINT (18.4241 -33.9249)

In [59]:
gdf.geometry

0    POINT (18.4241 -33.9249)
1    POINT (28.0473 -26.2041)
Name: geometry, dtype: geometry

In [61]:
gdf.geometry.geom_type

0    Point
1    Point
dtype: str

In [62]:
gdf["geometry"].x

0    18.4241
1    28.0473
dtype: float64

In [65]:
gdf["geometry"].y

0   -33.9249
1   -26.2041
dtype: float64

In [68]:
gdf[gdf["Population"] > 5000000]

KeyError: 'Population'

In [69]:
import geopandas as gpd
from shapely.geometry import Point

data = {
    "City": [
        "Cape Town", "Johannesburg", "Durban", "Pretoria", "Gqeberha",
        "Bloemfontein", "Polokwane", "Nelspruit", "Kimberley", "East London"
    ],
    "Population_M": [
        4.7, 6.3, 3.9, 2.5, 1.2,
        0.6, 0.8, 0.7, 0.3, 0.8
    ],
    "Province": [
        "Western Cape", "Gauteng", "KwaZulu-Natal", "Gauteng", "Eastern Cape",
        "Free State", "Limpopo", "Mpumalanga", "Northern Cape", "Eastern Cape"
    ],
    "geometry": [
        Point(18.4241, -33.9249),
        Point(28.0473, -26.2041),
        Point(31.0218, -29.8587),
        Point(28.1881, -25.7479),
        Point(25.6022, -33.9608),
        Point(26.2140, -29.0852),
        Point(29.4486, -23.9045),
        Point(30.9703, -25.4753),
        Point(24.7499, -28.7282),
        Point(27.9116, -33.0153)
    ]
}

gdf = gpd.GeoDataFrame(data, crs="EPSG:4326")

gdf

           City  Population_M       Province                  geometry
0     Cape Town           4.7   Western Cape  POINT (18.4241 -33.9249)
1  Johannesburg           6.3        Gauteng  POINT (28.0473 -26.2041)
2        Durban           3.9  KwaZulu-Natal  POINT (31.0218 -29.8587)
3      Pretoria           2.5        Gauteng  POINT (28.1881 -25.7479)
4      Gqeberha           1.2   Eastern Cape  POINT (25.6022 -33.9608)
5  Bloemfontein           0.6     Free State   POINT (26.214 -29.0852)
6     Polokwane           0.8        Limpopo  POINT (29.4486 -23.9045)
7     Nelspruit           0.7     Mpumalanga  POINT (30.9703 -25.4753)
8     Kimberley           0.3  Northern Cape  POINT (24.7499 -28.7282)
9   East London           0.8   Eastern Cape  POINT (27.9116 -33.0153)

In [70]:
gdf[gdf["Population_M"] > 1]

           City  Population_M       Province                  geometry
0     Cape Town           4.7   Western Cape  POINT (18.4241 -33.9249)
1  Johannesburg           6.3        Gauteng  POINT (28.0473 -26.2041)
2        Durban           3.9  KwaZulu-Natal  POINT (31.0218 -29.8587)
3      Pretoria           2.5        Gauteng  POINT (28.1881 -25.7479)
4      Gqeberha           1.2   Eastern Cape  POINT (25.6022 -33.9608)

In [ ]:
!pip install pysal

In [ ]:
import pysal
print (pysal.__version__)

In [ ]:
import geopandas as gpd
from libpysal.weights import Queen
from esda.moran import Moran
gpdf = gpd.read_file("data.shp")
weights = Queen.from_dataframe(gpdf)

In [ ]:
!pip install psycopg2-binary

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="my_database",
    user="postgres",
    password="your_password"
)

cursor = conn.cursor()

cursor.execute("""
    SELECT *
    FROM customers
    LIMIT 10;
""")

rows = cursor.fetchall()

for row in rows:
    print(row)

cursor.close()
conn.close()

In [ ]:
import pandas as pd
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="my_database",
    user="postgres",
    password="your_password"
)

df = pd.read_sql("""
    SELECT customer_id, sales
    FROM sales
    WHERE sales > 1000;
""", conn)

df

In [ ]:
SELECT
    name,
    population
FROM cities
WHERE population > 1000000;

In [ ]:
SELECT *
FROM locations
WHERE ST_DWithin(
    geometry,
    ST_SetSRID(ST_Point(28.0473, -26.2041), 4326),
    10000
);